name: new_version_plus
description: Check if your user has the most recent version of your Flutter app.
version: 0.0.12
homepage: https://github.com/CodesFirst/new_version_plus

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2
  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
